### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by rmatovu987** [SV3A/bBucket2gHub#1]
I am getting this error: `failed with status 404
(node:7061) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at BitbucketPuller.getRepoNames (.../bBucket2gHub/src/bitbucket/bitbucket-pull.js:96:29)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async main (.../bBucket2gHub/src/index.js:17:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7061) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7061) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.` I am not good with javascript so I don't know exactly what is wrong..

**Comment by SV3A** [comment]
I think this is due to some assumption not being met in regards to your repository versus how I've tested it with mine.
Are you sure that your environment variables are correct, specifically the "BITBUCKET_WORKSPACE" variable?

**Comment by rmatovu987** [comment]
Well, I have finally found the issue. The "BITBUCKET_WORKSPACE" variable expects the workspace id and not the name. I believe for your case while testing, your workspace name and id were the same. Mine are different and when I used the workspace id, it worked like a charm. 

However, for cases where I did not create the workspace, I don't know the id hence it doesn't work for such a situation.
