### ISSUE TITLE
How this behaves in terms of runing it the second time? 

### ISSUE THREAD

**Issue by deki23** [SV3A/bBucket2gHub#6]
Hey Svend,
I used this a few months back and would like to sync my new commits. 
Do I need to delete the previous repo so it doesn't make duplicates, or will it check the imported ones? Not sure what is the correct way to do it. Any suggestions?

**Comment by SV3A** [comment]
It's all matched by the hashes, so it should not create any duplicates.
This only case I can think of is if the history has been changed e.g. by a major rebase with a force push or similar.

**Comment by deki23** [comment]
Thanks for the info, and also this great package!
