### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by mufayed** [SV3A/bBucket2gHub#9]
I'm always getting the following error, Is there any solution?
Thanks..

![Screenshot 2023-03-06 at 2 50 46 pm](https://user-images.githubusercontent.com/49162143/223090029-cdebecff-91d5-40c9-98b2-ea6e774160c1.png)

**Comment by YvesJaques** [comment]
Check your bitbucket password

**Comment by mufayed** [comment]
I was using my password, but after creating an app password it worked fine, Thanks for your help.

> Check your bitbucket password, also put strings between quotation marks
